on:
  push:
    branches:
      - main
      - "release/**"
    paths:
      - 'src/**'
      - 'test/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'tsconfig.node.json'
      - 'tsconfig.app.json'
      - 'tsconfig.spec.json'
      - 'tsconfig.base.json'
  pull_request:
    branches:
      - main
      - "release/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2

      - name: Run Tests
        run: npm run test